pull_requests:
  do_not_increment_build_number: false
# branches:
  # only:
  # - appveyor-deploy-tests
image: Visual Studio 2017
configuration: Release
build:
  parallel: true                  # enable MSBuild parallel builds
  project: vMenu.sln              # path to Visual Studio solution or project
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: minimal
after_build:
  - cmd: copy README.md ..\build\README.md
  - cmd: copy LICENSE.md ..\build\LICENSE.md
  - ps: Invoke-WebRequest -OutFile '..\build\__resource.lua' https://vespura.com/vmenu/__resource.lua
  - cmd: 7z a vMenu-%APPVEYOR_REPO_TAG_NAME%.zip -r ..\build\*
artifacts:
  - path: vMenu-$(APPVEYOR_REPO_TAG_NAME).zip
deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: vMenu-$(APPVEYOR_REPO_TAG_NAME).zip
    draft: true
    prerelease: false
    auth_token: $(github_auth)
    on:
      branch: appveyor-deploy-tests # production release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only