pull_requests:
  do_not_increment_build_number: false
# branches:
  # only:
  # - production
image: Visual Studio 2017
configuration: Release
build:
  parallel: true
  project: vMenu.sln
  verbosity: minimal
after_build:
  - cmd: copy README.md ..\build\README.md
  - cmd: copy LICENSE.md ..\build\LICENSE.md
  - ps: Invoke-WebRequest -OutFile '..\build\__resource.lua' https://vespura.com/vmenu/__resource.lua
  - cmd: 7z a vMenu-%APPVEYOR_REPO_TAG_NAME%.zip -r ..\build\*
artifacts:
  - path: vMenu-$(APPVEYOR_REPO_TAG_NAME).zip
deploy:
  - provider: GitHub
    release: [Release] vMenu $(APPVEYOR_REPO_TAG_NAME)
    artifact: vMenu-$(APPVEYOR_REPO_TAG_NAME).zip
    draft: true
    prerelease: false
    auth_token: $(github_auth)
    on:
      branch: production
      APPVEYOR_REPO_TAG: true
    description: "vMenu version $(APPVEYOR_REPO_TAG_NAME)."